# Generated by Django 6.1.1 on 2026-09-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
